### ISSUE TITLE
AirConsole does not work with itch.io app browser

### ISSUE THREAD

**Issue by joemicmc** [AirConsole/airconsole-api#53]
I'm not sure if this is something you want to support, but embedded games don't run correctly in the itch.io app browser. Behind the scenes it uses Chrome, but for some reason the the client closes the websockets prematurely and it never manages to communicate with server.

### Details
- Version: itch.io app 25.3.0
- OS: Windows 10
- Steps: Download and launch html5 game (https://8bitape.itch.io/dungeoncrawl) from itch app

### Description
When the game is launched, websocket connections are closed:  
`WebSocket connection to 'wss://server-url' failed: WebSocket is closed before the connection is established.`

As a workaround, i display a splash screen of sorts that allows the user to launch the AirConsole game in their default browser:

![image](https://user-images.githubusercontent.com/7323103/46906475-fce85d80-cefb-11e8-93c5-f47892580214.png)

**Comment by fasterthanlime** [comment]
A few notes on the itch app:

  * There are some troubleshooting notes in the manual: https://itch.io/docs/itch/integrating/troubleshooting-guide.html
  * If you're on Windows, it installs to `%LOCALAPPDATA%/itch/app-25.3.0`
  * If you `set IMMEDIATE_NOSE_DIVE=1` (as an environment variable) before starting itch.exe, it'll open developer tools *before* launching an HTML5 game, which might give you more details than starting the game and only then pressing Shift+F12
  * Games are served from a custom protocol, `itch-cave://`, but it's registered as a "secure" protocol within chrome, so, for example, the Fetch API works, Websocket works, see https://fasterthanlime.itch.io/ws-test

Here are the versions it currently ships with (tl;dr Chrome 61)

![image](https://user-images.githubusercontent.com/7998310/46916768-4a79ce80-cfbf-11e8-919c-28f31c565b30.png)

---

I'm not familiar with how AirConsole works, so if anyone posts a few details about it I might be able to figure out what makes them not play together nice.

**Comment by andrin-n-dream** [comment]
`itch-cave://` is a problem. We require everything to be served over https or http.

**Comment by fasterthanlime** [comment]
> `itch-cave://` is a problem. We require everything to be served over https or http.

Can you expand on that a little bit? What are the technical reasons that make it so that games won't work unless the protocol happens to be `http` or `https`?

As I mentioned, that protocol, in the app, behaves exactly like `https` - all features are enabled for it (including WebSockets, Fetch, Web workers, anything https allows you to do in Chrome). It just happens to have a different name. I'm having a hard time understanding how that makes any difference to the AirConsole runtime (or how it's related to the error trace posted in the original message!)

(We cannot serve games over a protocol named "https", because it would either interfere with the actual https protocol, or would involve generating+trusting a local certificate, which has proved problematic in the past).
